INSERT INTO news_articles (title, content, summary, image_url, source_url, source_name, published_at, created_at, is_auto_generated) VALUES
('Boston Dynamics представляет новую версию робота Spot', 'Boston Dynamics анонсировала обновленную версию своего четвероногого робота Spot с улучшенной автономностью и новыми сенсорами.', 'Четвероногий робот Spot получил важные обновления', '/spot-robot.png', 'https://bostondynamics.com', 'Boston Dynamics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
('Революция в автоматизации производства: коботы нового поколения', 'Коллаборативные роботы (коботы) меняют промышленное производство. Новое поколение роботов может безопасно работать рядом с людьми.', 'Коботы открывают новые горизонты для промышленности', '/cobot-arm.png', 'https://ifr.org', 'IFR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
('Дроны в сельском хозяйстве: эффективность и экология', 'Беспилотные летательные аппараты все чаще используются в сельском хозяйстве для мониторинга посевов.', 'Технологии дронов revolutionize сельское хозяйство', '/agricultural-drone.png', 'https://dronedj.com', 'DroneDJ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO robot_catalog (name, category, description, price, official_website, image_url, specifications, created_at, updated_at) VALUES
('Boston Dynamics Spot', 'Мобильный робот', 'Четвероногий робот для промышленной инспекции и исследований.', 'от $74,500', 'https://www.bostondynamics.com/products/spot', '/spot-robot.png', 'Вес: 32.5 кг, Скорость: 1.6 м/с', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Universal Robots UR10e', 'Коллаборативный робот', 'Коллаборативный робот-манипулятор для промышленного производства.', 'от $46,000', 'https://www.universal-robots.com', '/cobot-arm.png', 'Грузоподъемность: 12.5 кг', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DJI Agras T40', 'Сельскохозяйственный дрон', 'Профессиональный дрон для опрыскивания полей и мониторинга посевов.', 'от $15,000', 'https://www.dji.com/agras-t40', '/agricultural-drone.png', 'Бак: 40 л', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('iRobot Roomba j7+', 'Бытовой робот', 'Умный робот-пылесос с функцией распознавания препятствий.', '$799', 'https://www.irobot.com', '/robot-vacuum.png', 'Автономность: 120 минут', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SoftBank Pepper', 'Сервисный робот', 'Гуманоидный робот для обслуживания клиентов.', 'от $25,000', 'https://www.softbankrobotics.com', '/humanoid-service-robot.png', 'Рост: 120 см', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO faq_items (question, answer, category, "order", created_at, updated_at) VALUES
('Что такое робототехника?', 'Робототехника — это междисциплинарная область науки и техники, занимающаяся проектированием, конструированием, программированием и применением роботов.', 'Основы', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Какие бывают типы роботов?', 'Роботы классифицируются по назначению: промышленные, сервисные, медицинские, исследовательские, военные, развлекательные и образовательные.', 'Основы', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Как начать изучать робототехнику?', 'Начните с основ программирования (Python, C++), электроники (Arduino, Raspberry Pi) и механики.', 'Обучение', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Сколько стоит собрать простого робота?', 'Простого учебного робота можно собрать от 5000 рублей. Набор Arduino с сенсорами и моторами стоит 3000-7000₽.', 'DIY', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Какие языки программирования используются в робототехнике?', 'Основные языки: C/C++, Python, Java, ROS. Для начинающих рекомендуется Python и Arduino IDE.', 'Программирование', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO diy_projects (title, description, content, difficulty, image_url, materials, steps, created_at, updated_at) VALUES
('Робот-манипулятор на базе Arduino', 'Создайте функциональный робот-манипулятор с сервоприводами.', 'Подробная инструкция по сборке робота-манипулятора с использованием Arduino.', 'Средний', '/diy-robot-arm.png', 'Arduino Uno, 5x сервоприводы MG996R, источник питания 5V 3A', '1. Печать деталей\n2. Сборка механики\n3. Подключение\n4. Загрузка кода\n5. Калибровка', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Робот-следопыт (Line Follower)', 'Соберите робота, который автоматически следует по черной линии.', 'Простой проект для начинающих. Робот использует ИК-сенсоры для определения линии.', 'Начальный', '/line-follower-robot.png', 'Arduino Nano, ИК-сенсоры x3, драйвер L298N, моторы', '1. Сборка шасси\n2. Установка моторов\n3. Монтаж сенсоров\n4. Подключение\n5. Программирование', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Умный робот-пылесос на ESP32', 'Создайте автономного робота-пылесоса с возможностью управления через Wi-Fi.', 'Продвинутый проект с использованием ESP32 и ультразвуковых сенсоров.', 'Продвинутый', '/diy-cleaning-robot.png', 'ESP32, ультразвуковые сенсоры HC-SR04 x4, моторы с энкодерами', '1. Проектирование\n2. Сборка механики\n3. Установка электроники\n4. Программирование\n5. Настройка Wi-Fi\n6. Тестирование', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
