import { zValidator } from "@hono/zod-validator";
import { Hono } from "hono";
import { z } from "zod";
import { authenticatedOnly, requireAdmin } from "../middleware/auth";
import type { HonoContext } from "../types";
import { newsArticles, robotCatalog, faqItems, diyProjects, chatMessages, usefulLinks } from "../db/schema";
import { eq } from "drizzle-orm";

export const adminRoutes = new Hono<HonoContext>()
  .use("*", authenticatedOnly, requireAdmin)
  
  .post("/news", zValidator("json", z.object({
    title: z.string().min(1),
    content: z.string().min(1),
    summary: z.string().optional(),
    imageUrl: z.string().optional(),
    videoUrl: z.string().optional(),
    sourceUrl: z.string().optional(),
    sourceName: z.string().optional(),
  })), async (c) => {
    const db = c.get("db");
    const data = c.req.valid("json");
    
    const article = await db.insert(newsArticles).values({
      ...data,
      publishedAt: new Date(),
      createdAt: new Date(),
      isAutoGenerated: false,
    }).returning().get();
    
    return c.json(article);
  })
  
  .put("/news/:id", zValidator("param", z.object({ id: z.string() })), zValidator("json", z.object({
    title: z.string().min(1),
    content: z.string().min(1),
    summary: z.string().optional(),
    imageUrl: z.string().optional(),
    videoUrl: z.string().optional(),
    sourceUrl: z.string().optional(),
    sourceName: z.string().optional(),
  })), async (c) => {
    const db = c.get("db");
    const { id } = c.req.valid("param");
    const data = c.req.valid("json");
    
    const article = await db.update(newsArticles)
      .set(data)
      .where(eq(newsArticles.id, parseInt(id)))
      .returning()
      .get();
    
    return c.json(article);
  })
  
  .delete("/news/:id", zValidator("param", z.object({ id: z.string() })), async (c) => {
    const db = c.get("db");
    const { id } = c.req.valid("param");
    
    await db.delete(newsArticles).where(eq(newsArticles.id, parseInt(id)));
    
    return c.json({ success: true });
  })
  
  .post("/robots", zValidator("json", z.object({
    name: z.string().min(1),
    category: z.string().min(1),
    description: z.string().min(1),
    price: z.string().optional(),
    officialWebsite: z.string().optional(),
    imageUrl: z.string().optional(),
    specifications: z.string().optional(),
  })), async (c) => {
    const db = c.get("db");
    const data = c.req.valid("json");
    
    const robot = await db.insert(robotCatalog).values({
      ...data,
      createdAt: new Date(),
      updatedAt: new Date(),
    }).returning().get();
    
    return c.json(robot);
  })
  
  .put("/robots/:id", zValidator("param", z.object({ id: z.string() })), zValidator("json", z.object({
    name: z.string().min(1),
    category: z.string().min(1),
    description: z.string().min(1),
    price: z.string().optional(),
    officialWebsite: z.string().optional(),
    imageUrl: z.string().optional(),
    specifications: z.string().optional(),
  })), async (c) => {
    const db = c.get("db");
    const { id } = c.req.valid("param");
    const data = c.req.valid("json");
    
    const robot = await db.update(robotCatalog)
      .set({ ...data, updatedAt: new Date() })
      .where(eq(robotCatalog.id, parseInt(id)))
      .returning()
      .get();
    
    return c.json(robot);
  })
  
  .delete("/robots/:id", zValidator("param", z.object({ id: z.string() })), async (c) => {
    const db = c.get("db");
    const { id } = c.req.valid("param");
    
    await db.delete(robotCatalog).where(eq(robotCatalog.id, parseInt(id)));
    
    return c.json({ success: true });
  })
  
  .post("/faq", zValidator("json", z.object({
    question: z.string().min(1),
    answer: z.string().min(1),
    category: z.string().optional(),
    order: z.number().optional(),
  })), async (c) => {
    const db = c.get("db");
    const data = c.req.valid("json");
    
    const item = await db.insert(faqItems).values({
      ...data,
      createdAt: new Date(),
      updatedAt: new Date(),
    }).returning().get();
    
    return c.json(item);
  })
  
  .put("/faq/:id", zValidator("param", z.object({ id: z.string() })), zValidator("json", z.object({
    question: z.string().min(1),
    answer: z.string().min(1),
    category: z.string().optional(),
    order: z.number().optional(),
  })), async (c) => {
    const db = c.get("db");
    const { id } = c.req.valid("param");
    const data = c.req.valid("json");
    
    const item = await db.update(faqItems)
      .set({ ...data, updatedAt: new Date() })
      .where(eq(faqItems.id, parseInt(id)))
      .returning()
      .get();
    
    return c.json(item);
  })
  
  .delete("/faq/:id", zValidator("param", z.object({ id: z.string() })), async (c) => {
    const db = c.get("db");
    const { id } = c.req.valid("param");
    
    await db.delete(faqItems).where(eq(faqItems.id, parseInt(id)));
    
    return c.json({ success: true });
  })
  
  .post("/diy", zValidator("json", z.object({
    title: z.string().min(1),
    description: z.string().min(1),
    content: z.string().min(1),
    difficulty: z.string().min(1),
    imageUrl: z.string().optional(),
    materials: z.string().optional(),
    steps: z.string().optional(),
  })), async (c) => {
    const db = c.get("db");
    const data = c.req.valid("json");
    
    const project = await db.insert(diyProjects).values({
      ...data,
      createdAt: new Date(),
      updatedAt: new Date(),
    }).returning().get();
    
    return c.json(project);
  })
  
  .put("/diy/:id", zValidator("param", z.object({ id: z.string() })), zValidator("json", z.object({
    title: z.string().min(1),
    description: z.string().min(1),
    content: z.string().min(1),
    difficulty: z.string().min(1),
    imageUrl: z.string().optional(),
    materials: z.string().optional(),
    steps: z.string().optional(),
  })), async (c) => {
    const db = c.get("db");
    const { id } = c.req.valid("param");
    const data = c.req.valid("json");
    
    const project = await db.update(diyProjects)
      .set({ ...data, updatedAt: new Date() })
      .where(eq(diyProjects.id, parseInt(id)))
      .returning()
      .get();
    
    return c.json(project);
  })
  
  .delete("/diy/:id", zValidator("param", z.object({ id: z.string() })), async (c) => {
    const db = c.get("db");
    const { id } = c.req.valid("param");
    
    await db.delete(diyProjects).where(eq(diyProjects.id, parseInt(id)));
    
    return c.json({ success: true });
  })
  
  .delete("/chat/messages/:id", zValidator("param", z.object({ id: z.string() })), async (c) => {
    const db = c.get("db");
    const { id } = c.req.valid("param");
    
    await db.update(chatMessages)
      .set({ isDeleted: true })
      .where(eq(chatMessages.id, parseInt(id)));
    
    return c.json({ success: true });
  })
  
  .post("/useful-links", zValidator("json", z.object({
    title: z.string().min(1),
    description: z.string().min(1),
    url: z.string().url(),
    category: z.string().min(1),
    iconUrl: z.string().optional(),
    order: z.number().optional(),
  })), async (c) => {
    const db = c.get("db");
    const data = c.req.valid("json");
    
    const link = await db.insert(usefulLinks).values({
      ...data,
      createdAt: new Date(),
      updatedAt: new Date(),
    }).returning().get();
    
    return c.json(link);
  })
  
  .put("/useful-links/:id", zValidator("param", z.object({ id: z.string() })), zValidator("json", z.object({
    title: z.string().min(1),
    description: z.string().min(1),
    url: z.string().url(),
    category: z.string().min(1),
    iconUrl: z.string().optional(),
    order: z.number().optional(),
  })), async (c) => {
    const db = c.get("db");
    const { id } = c.req.valid("param");
    const data = c.req.valid("json");
    
    const link = await db.update(usefulLinks)
      .set({ ...data, updatedAt: new Date() })
      .where(eq(usefulLinks.id, parseInt(id)))
      .returning()
      .get();
    
    return c.json(link);
  })
  
  .delete("/useful-links/:id", zValidator("param", z.object({ id: z.string() })), async (c) => {
    const db = c.get("db");
    const { id } = c.req.valid("param");
    
    await db.delete(usefulLinks).where(eq(usefulLinks.id, parseInt(id)));
    
    return c.json({ success: true });
  });
