import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { apiClient } from "@/lib/api-client";
import { ArrowLeft, Calendar, ExternalLink } from "lucide-react";
import { motion } from "framer-motion";

export default function News() {
  const { data: news, isLoading } = useQuery({
    queryKey: ["news"],
    queryFn: async () => {
      const res = await apiClient.api.news.$get();
      if (!res.ok) throw new Error("Failed to fetch news");
      return res.json();
    },
  });

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-blue-950 to-slate-900 text-white">
      <nav className="sticky top-0 z-50 backdrop-blur-md bg-slate-950/80 border-b border-white/10 px-8 py-4">
        <div className="container mx-auto flex items-center justify-between">
          <Link to="/" className="flex items-center gap-3">
            <img src="/logo.png" alt="PROроботов" className="h-10 w-auto" />
            <span className="text-xl font-bold text-blue-200">PROроботов</span>
          </Link>
          <Link
            to="/"
            className="flex items-center gap-2 text-blue-300 hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            На главную
          </Link>
        </div>
      </nav>

      <main className="container mx-auto px-8 py-16">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12"
        >
          <h1 className="text-5xl font-bold mb-4 bg-gradient-to-r from-blue-300 to-cyan-300 bg-clip-text text-transparent">
            Новости робототехники
          </h1>
          <p className="text-blue-300 text-lg">
            Последние новости и обновления из мира роботов
          </p>
        </motion.div>

        {isLoading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[1, 2, 3, 4, 5, 6].map((i) => (
              <div
                key={i}
                className="rounded-xl backdrop-blur-sm bg-white/5 border border-white/10 p-6 animate-pulse"
              >
                <div className="h-48 bg-white/10 rounded-lg mb-4" />
                <div className="h-6 bg-white/10 rounded mb-2" />
                <div className="h-4 bg-white/10 rounded w-3/4" />
              </div>
            ))}
          </div>
        ) : news && news.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {news.map((article: any, index: number) => (
              <motion.div
                key={article.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
              >
                <Link to={`/news/${article.id}`}>
                  <div className="group rounded-xl overflow-hidden backdrop-blur-sm bg-white/5 border border-white/10 hover:border-cyan-400/50 transition-all duration-300 h-full">
                    {article.imageUrl && (
                      <div className="relative overflow-hidden">
                        <img
                          src={article.imageUrl}
                          alt={article.title}
                          className="w-full h-56 object-cover group-hover:scale-105 transition-transform duration-300"
                        />
                        {article.isAutoGenerated && (
                          <span className="absolute top-3 right-3 px-2 py-1 text-xs rounded-full bg-cyan-500/80 text-white">
                            Авто
                          </span>
                        )}
                      </div>
                    )}
                    <div className="p-6">
                      <h3 className="text-xl font-semibold mb-3 text-blue-100 group-hover:text-cyan-300 transition-colors">
                        {article.title}
                      </h3>
                      {article.summary && (
                        <p className="text-sm text-blue-300 line-clamp-3 mb-4">
                          {article.summary}
                        </p>
                      )}
                      <div className="flex items-center justify-between text-xs text-blue-400">
                        <div className="flex items-center gap-2">
                          <Calendar className="w-4 h-4" />
                          {new Date(article.publishedAt).toLocaleDateString("ru-RU")}
                        </div>
                        {article.sourceUrl && (
                          <div className="flex items-center gap-1 text-cyan-400">
                            <ExternalLink className="w-3 h-3" />
                            {article.sourceName || "Источник"}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                </Link>
              </motion.div>
            ))}
          </div>
        ) : (
          <div className="text-center py-16">
            <p className="text-blue-300 text-lg">Новостей пока нет</p>
          </div>
        )}
      </main>
    </div>
  );
}
